# Generated by Django 4.1.7 on 2023-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('school_no', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'school_no', 'date_of_birth', 'register_date'],
            },
        ),
    ]
